# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa69c0c5c7c76c5268443b3ac744b79a20c1026a21a500db7516b12b0c17abf54476fac7468e76aa2ce66979ca6e1323138914d506c939b4c238e25ff1b24e6f

test:
  secret_key_base: 3cdf111d43f6f7173369d5baaeb330f105ab3481938c8330407057c6c80a8f36a1a15d8eb005dde01e389b0ce015c52eeb4fb5089692964585cd6c0078574652

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
